myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path # re_path is regular expression
from . import views # import view.py
from django.conf.urls.static import static # import to upload image
from django.conf import settings # import to upload image
from django.views.static import serve # server func used during development

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage), # homepage function in views.py
    path('about/', views.about), # about page function in views.py
    path('posts/', include('posts.urls')), # to look inside posts app
    path('users/', include('users.urls')) # to look inside posts app
]

# used both imported at the top to use in url patterns
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views # import view.py

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"), # homepage function in views.py
    path('new-post/', views.post_new, name="new-post"), # 
    path('<slug:slug>', views.post_page, name="page"), # use slug path converted, left and parameter
]

myproject/users/urls.py
from django.urls import path
from . import views # import view.py

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"), # homepage function in views.py
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User # add author of the post
# Create your models here.

class Post(models.Model):
    # define our model fields , slug is urls
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    # means not requiring an image if we dont have one
    banner = models.ImageField(default='fallback.png', blank=True)
    # author is the foreign key into 2 tables
    # on_delete thats telling the database how to handle data if this relationship is deleted
    # CASCADE meanse if deleted. it delete all post too
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','slug','banner']

myproject/myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # should we see once we go to Home page
    # return HttpResponse("Hello World! I'm #.")
    return render(request, 'home.html')

def about(request):
    # should we see once we go to About page
    # return HttpResponse("My About page.")
    return render(request, 'about.html')

myproject/posts/views.py
from django.shortcuts import render, redirect
from .models import Post #import the Post
from django.contrib.auth.decorators import login_required # decorator on function,
from . import forms
# Create your views here.

def posts_list(request):
    posts = Post.objects.all().order_by('-date') # get all of the object for us, order by descending way minus sign
    return render(request, 'posts/posts_list.html', {'posts': posts}) #add posts in dictionary, passing data on the template

def post_page(request, slug): # create function for post page
    post = Post.objects.get(slug=slug) # pass to get one post we have that matches slug
    return render(request, 'posts/post_page.html', {'post': post}) #add posts in dictionary, passing data on the template

@login_required(login_url="/users/login") #checks when function runs to see if user login
def post_new(request):
    if request.method == 'POST': # should be POST request
        form = forms.CreatePost(request.POST, request.FILES) #sending also an image file
        if form.is_valid(): # validate what submitted against the model
            # save with user
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list')
    else: # else is the GET request
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', { 'form': form })

myproject/users/views.py
from django.shortcuts import render, redirect # after successfully submitted it will  redirect to post list
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm # importing a form
from django.contrib.auth import login, logout # contrib.auth to log user in, import logout

# Create your views here.
def register_view(request):
    # if the form has been submitted, this function will handle this request
    if request.method == "POST":
        form = UserCreationForm(request.POST) #form validation
        if form.is_valid(): # will validate if true
                login(request, form.save()) # this will return user value
                return redirect("posts:list")
    else:
         form = UserCreationForm()
    form = UserCreationForm()
    return render(request, "users/register.html", { "form": form })

def login_view(request):
    if request.method == "POST":
          form = AuthenticationForm(data=request.POST)
          if form.is_valid():
               login(request, form.get_user()) # login to request and it will return user
               #getting value of field we name next in the form
               if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
               else:
                    return redirect("posts:list")
    else: # GET request
         form = AuthenticationForm()
    return render(request, "users/login.html", { "form": form })

def logout_view(request):
     if request.method == "POST":
          logout(request)
          return redirect("posts:list")

myproject/posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <!--action is link to urls.py name="new-post"-->
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            <!--need the content of the form-->
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Add Post</button>
        </form>
    </section>
{% endblock %}

myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
        <img 
            class="banner"
            src="{{ post.banner.url }}" 
            alt="{{ post.title }}"
        />
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock %}

myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
    <h1>Posts</h1>

    {% for post in posts %}
        <article class="post">
            <h2>
                <a href="{% url 'posts:page' slug=post.slug %}">
                    {{ post.title }}
                </a>
            </h2>
            <p>{{ post.date }} by {{ post.author }}</p>
            <p>{{ post.body }}</p>
        </article>
    {% endfor %}
</section>
{% endblock %}

myproject/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

myproject/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">
            <!--Helps accessibility-->
            <span role="img" aria-label="Home" title="Home">🏠</span>
        </a> | 
        <a href="/about">
            <span role="img" aria-label="About" title="About">😀</span>
        </a> | 
        <a href="{% url 'posts:list' %}">
            <span role="img" aria-label="Posts" title="Posts">📰</span>
        </a> |
        <!--checking if user is login-->
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}"> <!--based on the users > urls.py-->
                <span role="img" aria-label="New Post" title="New Post">🆕</span>
            </a> |
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button" aria-label="User Logout" title="User Logout">👋</button>
            </form>
        {% else %}
        <!--will show if not login-->
            <a href="{% url 'users:register' %}"> <!--based on the users > urls.py-->
                <span role="img" aria-label="User Registration" title="User Registration">🚀</span>
            </a> |
            <a href="{% url 'users:login' %}"> <!--based on the users > urls.py-->
                <span role="img" aria-label="User Login" title="User Login">🔏</span>
            </a>
        {% endif %}
        <!-- refering to the name="posts" gave in the url.py-->
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

myproject/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <h1>User Login</h1>
    <form class="form-with-validation" action="{% url 'users:login' %}" method="post"> <!--action value is from urls.py-->
        {% csrf_token %}
        {{ form }}
        <!--this input will only be added if exist--> 
        {% if request.GET.next %}
            <input type="hidden" name="next" value={{ request.GET.next }} />
        {% endif %}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}

myproject/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="{% url 'users:register' %}" method="post"> <!--action value is from urls.py-->
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}